### ISSUE TITLE
feat(service): 支持跳过IPv4获取配置与更新次数配置。 

### ISSUE THREAD

**Issue by lqsbg26** [CarmJos/AliDDNS-Updater#1]
在白群晖DS213j上，DMS版本6.2.4（Linux version 3.2.40 ），装了Java后可以运行此jar文件，并成功更新AliDDNS的IPv6记录。

不过，我只需要更新IPv6记录，所以在config文件中去掉了IPv4检查的服务器，然后一运行，IPv4检查的那行配置又回来了。用VI修改的配置文件，而且存盘后用vi再次进入检查过，确实修改成功了。但是程序一运行，就会还原。

另外还有一个想法，能否增加一个开关，让这个程序只运行一次，因为不想让它始终运行，而且可能日后又些与其他进程脚本联动的需求。

**Comment by CarmJos** [comment]
您好，关于IPv4地址获取问题，我在设计的时候并没有支持IPv4地址的“留空以跳过获取”功能，因此每次启动时由于未读取到地址会自动添加回配置文件以便配置。我尝试在下个版本中支持该功能。

关于程序运行次数问题，我将在下一版本中提供“`sevice.times`”配置，以便规定该程序运行的次数。
