### ISSUE TITLE
能否增加日志功能

### ISSUE THREAD

**Issue by lqsbg26** [CarmJos/AliDDNS-Updater#3]
我目前是在白群晖上使用这个工具，调试时用命令行运行，能看到返回的消息。但日常使用是通过cron或systemd等方式，使其随系统启动，或定期运行的，总之是后台运行且无交互界面。由于DNS传播的延迟性质，其实我对此工具的运行状态是心里没底的。

所以能否在config里定义以下日志的输出与否，以及日志路径。这样在排查时可以看到最近几轮的运行结果或状态。谢谢

**Comment by CarmJos** [comment]
您好，请在使用指定命令时对控制台输出进行文件转储以实现该功能。
